baseURL = "https://droppedbits.com/"
languageCode = "en-ca"
title = "Dropped Bits"
theme = "db-theme"
footnoteReturnLinkContents = "⮐"

[params]
  author = "Angelo Stavrow"

[permalinks]
  news = "/news/:year/:month/:day/:filename"
  apps = "/apps/:title"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true